### ISSUE TITLE
Finished HW

### ISSUE THREAD

**Issue by rauchi12** [htl-perg-2019-20-5ahif/contact-list-exercise-rauchi12#1]
Hi @rstropek,
I implemented all the requests.
Everything should work fine.

Greetings,
Lukas

**Comment by rstropek** [comment]
Avoid checking in unnecessary files (e.g. *.vscode*, *bin*, *obj*).

**Comment by rstropek** [comment]
Otherwise well done. Added some minor feedback as comments. The extra point is yours.

Greetings,
Rainer Stropek
